'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFlight
    Public Property flightID As Integer
    Public Property departFROM As String
    Public Property arriveAT As String
    Public Property distance As Decimal
    Public Property active As Boolean

    Public Overridable Property tblAirport As tblAirport
    Public Overridable Property tblAirport1 As tblAirport

End Class
