'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class bit3444_projectdata
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=bit3444_projectdata")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblProjectHours() As DbSet(Of tblProjectHour)
    Public Overridable Property tblProjects() As DbSet(Of tblProject)
    Public Overridable Property tblStaffs() As DbSet(Of tblStaff)
    Public Overridable Property tblStaffClassifications() As DbSet(Of tblStaffClassification)
    Public Overridable Property tblStaffRates() As DbSet(Of tblStaffRate)
    Public Overridable Property vwTotalHours() As DbSet(Of vwTotalHour)
    Public Overridable Property vwTotalProjectCosts() As DbSet(Of vwTotalProjectCost)
    Public Overridable Property vwWeeklyHoursByStaffProjects() As DbSet(Of vwWeeklyHoursByStaffProject)

End Class
