'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblStaffRate
    Public Property staffid As Integer
    Public Property projectid As Integer
    Public Property rate As Decimal

    Public Overridable Property tblProject As tblProject
    Public Overridable Property tblStaff As tblStaff

End Class
