'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblStaffClassification
    Public Property classificationid As Integer
    Public Property classification As String

    Public Overridable Property tblProjectHours As ICollection(Of tblProjectHour) = New HashSet(Of tblProjectHour)
    Public Overridable Property tblStaffs As ICollection(Of tblStaff) = New HashSet(Of tblStaff)

End Class
